GET http://localhost:3000/users

###

POST http://localhost:3000/users 


{
"name": "logintest", 
"password": "passwordtest"
}

###

POST http://localhost:3000/login 

{
"name": "logintest", "password": "passwordtest"
}